/// Description
Class Formation.Msg.FormationSelectByIdRequest Extends Ens.Request
{

/// Description
Property ID As %Integer;

Storage Default
{
<Data name="FormationSelectByIdRequestDefaultData">
<Subscript>"FormationSelectByIdRequest"</Subscript>
<Value name="1">
<Value>ID</Value>
</Value>
</Data>
<DefaultData>FormationSelectByIdRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
