/// Description
Class Formation.Msg.FormationInsertResponse Extends Ens.Response
{

/// Description
Property Rand As %Integer;

/// Description
Property ID As %String;

Storage Default
{
<Data name="FormationInsertResponseDefaultData">
<Subscript>"FormationInsertResponse"</Subscript>
<Value name="1">
<Value>Rand</Value>
</Value>
<Value name="2">
<Value>ID</Value>
</Value>
</Data>
<DefaultData>FormationInsertResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
