/// Description
Class Formation.Msg.FormationSelectByIdResponse Extends Ens.Response
{

/// Description
Property Formation As Formation.Obj.Formation;

Storage Default
{
<Data name="FormationSelectByIdResponseDefaultData">
<Subscript>"FormationSelectByIdResponse"</Subscript>
<Value name="1">
<Value>Formation</Value>
</Value>
</Data>
<DefaultData>FormationSelectByIdResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
