/// Description
Class Formation.Msg.FormationDeleteByIdRequest Extends Ens.Request
{

/// Description
Property ID As %Integer;

Storage Default
{
<Data name="FormationDeleteByIdRequesstDefaultData">
<Subscript>"FormationDeleteByIdRequesst"</Subscript>
<Value name="1">
<Value>ID</Value>
</Value>
</Data>
<DefaultData>FormationDeleteByIdRequesstDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
