/// Description
Class Formation.Msg.FormationUpdateByIdResponse Extends Ens.Response
{

Property Formation As Formation.Obj.Formation;

Storage Default
{
<Data name="FormationUpdateByIdResponseDefaultData">
<Subscript>"FormationUpdateByIdResponse"</Subscript>
<Value name="1">
<Value>Formation</Value>
</Value>
</Data>
<DefaultData>FormationUpdateByIdResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
