Class Formation.Msg.FromationRestActionResponse Extends Ens.Response
{

/// ForamtionResponse
Property Formation As Formation.Obj.Formation;

Storage Default
{
<Data name="FromationRestActionResponseDefaultData">
<Subscript>"FromationRestActionResponse"</Subscript>
<Value name="1">
<Value>Formation</Value>
</Value>
</Data>
<DefaultData>FromationRestActionResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
