zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")

zn "USER"
; run installer to create namespace
do $SYSTEM.OBJ.Load("/tmp/iris/Installer.cls", "ck")
set sc = ##class(App.Installer).setup() 

zw $SYSTEM.OBJ.ImportDir("/tmp/iris/src", "*.cls", "cubk", .tErrors, 1)

zw ##class(Ens.Config.Credentials).SetCredential("Postgre","DemoData","DemoData",1)

zw ##class(Ens.Director).SetAutoStart("Grongier.Example.Production")

h